{"name": "adding new address", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-csa-c-content-id='nav_ya_signin']\"}\n  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7862352A2+57122]\n\t(No symbol) [0x00007FF7861AEA92]\n\t(No symbol) [0x00007FF78607E3AB]\n\t(No symbol) [0x00007FF7860B7D3E]\n\t(No symbol) [0x00007FF7860B7E2C]\n\t(No symbol) [0x00007FF7860F0B67]\n\t(No symbol) [0x00007FF7860D701F]\n\t(No symbol) [0x00007FF7860EEB82]\n\t(No symbol) [0x00007FF7860D6DB3]\n\t(No symbol) [0x00007FF7860AD2B1]\n\t(No symbol) [0x00007FF7860AE494]\n\tGetHandleVerifier [0x00007FF7864DEF82+2849794]\n\tGetHandleVerifier [0x00007FF786531D24+3189156]\n\tGetHandleVerifier [0x00007FF78652ACAF+3160367]\n\tGetHandleVerifier [0x00007FF7862C6D06+653702]\n\t(No symbol) [0x00007FF7861BA208]\n\t(No symbol) [0x00007FF7861B62C4]\n\t(No symbol) [0x00007FF7861B63F6]\n\t(No symbol) [0x00007FF7861A67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_address.py\", line 13, in step_impl\n    context.login_page = context.homepage.click_on_my_account()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\home_page.py\", line 19, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 32, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I logged into my account and got navigated to Homepage", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-csa-c-content-id='nav_ya_signin']\"}\n  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7862352A2+57122]\n\t(No symbol) [0x00007FF7861AEA92]\n\t(No symbol) [0x00007FF78607E3AB]\n\t(No symbol) [0x00007FF7860B7D3E]\n\t(No symbol) [0x00007FF7860B7E2C]\n\t(No symbol) [0x00007FF7860F0B67]\n\t(No symbol) [0x00007FF7860D701F]\n\t(No symbol) [0x00007FF7860EEB82]\n\t(No symbol) [0x00007FF7860D6DB3]\n\t(No symbol) [0x00007FF7860AD2B1]\n\t(No symbol) [0x00007FF7860AE494]\n\tGetHandleVerifier [0x00007FF7864DEF82+2849794]\n\tGetHandleVerifier [0x00007FF786531D24+3189156]\n\tGetHandleVerifier [0x00007FF78652ACAF+3160367]\n\tGetHandleVerifier [0x00007FF7862C6D06+653702]\n\t(No symbol) [0x00007FF7861BA208]\n\t(No symbol) [0x00007FF7861B62C4]\n\t(No symbol) [0x00007FF7861B63F6]\n\t(No symbol) [0x00007FF7861A67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_address.py\", line 13, in step_impl\n    context.login_page = context.homepage.click_on_my_account()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\home_page.py\", line 19, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 32, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "35567c1d-c292-4c32-9a6d-bb3213b0d19f-attachment.png", "type": "image/png"}], "start": 1693563974104, "stop": 1693563974408}, {"name": "When I click on my account and go to address option", "status": "skipped", "start": 1693563976995, "stop": 1693563976996}, {"name": "And click on add a new address", "status": "skipped", "start": 1693563976996, "stop": 1693563976996}, {"name": "Then entered all the details and added it", "status": "skipped", "start": 1693563976996, "stop": 1693563976996}], "start": 1693563938887, "stop": 1693563976996, "uuid": "d0f397d8-d243-4d2e-b895-4536450b4c38", "historyId": "12dd1a5d88f4de8a6e7a648477971cb2", "fullName": "print transactions history: adding new address", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "add_address"}, {"name": "feature", "value": "print transactions history"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}