{"name": "Login with valid phone number and invalid password -- @1.3 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-csa-c-content-id='nav_ya_signin']\"}\n  (Session info: chrome=116.0.5845.141); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7DEA552A2+57122]\n\t(No symbol) [0x00007FF7DE9CEA92]\n\t(No symbol) [0x00007FF7DE89E3AB]\n\t(No symbol) [0x00007FF7DE8D7D3E]\n\t(No symbol) [0x00007FF7DE8D7E2C]\n\t(No symbol) [0x00007FF7DE910B67]\n\t(No symbol) [0x00007FF7DE8F701F]\n\t(No symbol) [0x00007FF7DE90EB82]\n\t(No symbol) [0x00007FF7DE8F6DB3]\n\t(No symbol) [0x00007FF7DE8CD2B1]\n\t(No symbol) [0x00007FF7DE8CE494]\n\tGetHandleVerifier [0x00007FF7DECFEF82+2849794]\n\tGetHandleVerifier [0x00007FF7DED51D24+3189156]\n\tGetHandleVerifier [0x00007FF7DED4ACAF+3160367]\n\tGetHandleVerifier [0x00007FF7DEAE6D06+653702]\n\t(No symbol) [0x00007FF7DE9DA208]\n\t(No symbol) [0x00007FF7DE9D62C4]\n\t(No symbol) [0x00007FF7DE9D63F6]\n\t(No symbol) [0x00007FF7DE9C67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 9, in step_impl\n    context.login_page = context.homepage.click_on_my_account()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\home_page.py\", line 19, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 32, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigated to Login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-csa-c-content-id='nav_ya_signin']\"}\n  (Session info: chrome=116.0.5845.141); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF7DEA552A2+57122]\n\t(No symbol) [0x00007FF7DE9CEA92]\n\t(No symbol) [0x00007FF7DE89E3AB]\n\t(No symbol) [0x00007FF7DE8D7D3E]\n\t(No symbol) [0x00007FF7DE8D7E2C]\n\t(No symbol) [0x00007FF7DE910B67]\n\t(No symbol) [0x00007FF7DE8F701F]\n\t(No symbol) [0x00007FF7DE90EB82]\n\t(No symbol) [0x00007FF7DE8F6DB3]\n\t(No symbol) [0x00007FF7DE8CD2B1]\n\t(No symbol) [0x00007FF7DE8CE494]\n\tGetHandleVerifier [0x00007FF7DECFEF82+2849794]\n\tGetHandleVerifier [0x00007FF7DED51D24+3189156]\n\tGetHandleVerifier [0x00007FF7DED4ACAF+3160367]\n\tGetHandleVerifier [0x00007FF7DEAE6D06+653702]\n\t(No symbol) [0x00007FF7DE9DA208]\n\t(No symbol) [0x00007FF7DE9D62C4]\n\t(No symbol) [0x00007FF7DE9D63F6]\n\t(No symbol) [0x00007FF7DE9C67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 9, in step_impl\n    context.login_page = context.homepage.click_on_my_account()\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\home_page.py\", line 19, in click_on_my_account\n    self.click_on_element(\"my_account_option_xpath\", self.my_account_option_xpath)\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 32, in click_on_element\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "56e9f3b5-77e2-46ef-be38-32c674805677-attachment.png", "type": "image/png"}], "start": 1693810780548, "stop": 1693810780695}, {"name": "When I enter valid phone number as \"8019713239\" and invalid password as \"Harish@AMAZON33\" into the fields", "status": "skipped", "start": 1693810783356, "stop": 1693810783356}, {"name": "And I click on Login button", "status": "skipped", "start": 1693810783356, "stop": 1693810783356}, {"name": "Then I should get a proper warning message on password page", "status": "skipped", "start": 1693810783356, "stop": 1693810783356}], "parameters": [{"name": "number", "value": "8019713239"}, {"name": "password", "value": "Harish@AMAZON33"}], "start": 1693810741912, "stop": 1693810783356, "uuid": "2b47d9a1-2bcc-4070-b7f1-484af913f0fe", "historyId": "9579b61a38b537dcda449bd87b6fa29d", "fullName": "Login Functionality: Login with valid phone number and invalid password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login"}, {"name": "feature", "value": "Login Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}