{"name": "adding new address", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//h4[@class='a-alert-heading']\"}\n  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF61C2852A2+57122]\n\t(No symbol) [0x00007FF61C1FEA92]\n\t(No symbol) [0x00007FF61C0CE3AB]\n\t(No symbol) [0x00007FF61C107D3E]\n\t(No symbol) [0x00007FF61C107E2C]\n\t(No symbol) [0x00007FF61C140B67]\n\t(No symbol) [0x00007FF61C12701F]\n\t(No symbol) [0x00007FF61C13EB82]\n\t(No symbol) [0x00007FF61C126DB3]\n\t(No symbol) [0x00007FF61C0FD2B1]\n\t(No symbol) [0x00007FF61C0FE494]\n\tGetHandleVerifier [0x00007FF61C52EF82+2849794]\n\tGetHandleVerifier [0x00007FF61C581D24+3189156]\n\tGetHandleVerifier [0x00007FF61C57ACAF+3160367]\n\tGetHandleVerifier [0x00007FF61C316D06+653702]\n\t(No symbol) [0x00007FF61C20A208]\n\t(No symbol) [0x00007FF61C2062C4]\n\t(No symbol) [0x00007FF61C2063F6]\n\t(No symbol) [0x00007FF61C1F67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_address.py\", line 42, in step_impl\n    assert context.add_address.verify_text(\"Address saved\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\add_address_page.py\", line 50, in verify_text\n    return self.contains(\"add_address_text_xpath\", self.add_address_text_xpath, a)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 15, in contains\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I logged into my account and got navigated to Homepage", "status": "passed", "start": 1693473409315, "stop": 1693473435317}, {"name": "When I click on my account and go to address option", "status": "passed", "start": 1693473435317, "stop": 1693473472151}, {"name": "And click on add a new address", "status": "passed", "start": 1693473472151, "stop": 1693473474750}, {"name": "Then entered all the details and added it", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//h4[@class='a-alert-heading']\"}\n  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF61C2852A2+57122]\n\t(No symbol) [0x00007FF61C1FEA92]\n\t(No symbol) [0x00007FF61C0CE3AB]\n\t(No symbol) [0x00007FF61C107D3E]\n\t(No symbol) [0x00007FF61C107E2C]\n\t(No symbol) [0x00007FF61C140B67]\n\t(No symbol) [0x00007FF61C12701F]\n\t(No symbol) [0x00007FF61C13EB82]\n\t(No symbol) [0x00007FF61C126DB3]\n\t(No symbol) [0x00007FF61C0FD2B1]\n\t(No symbol) [0x00007FF61C0FE494]\n\tGetHandleVerifier [0x00007FF61C52EF82+2849794]\n\tGetHandleVerifier [0x00007FF61C581D24+3189156]\n\tGetHandleVerifier [0x00007FF61C57ACAF+3160367]\n\tGetHandleVerifier [0x00007FF61C316D06+653702]\n\t(No symbol) [0x00007FF61C20A208]\n\t(No symbol) [0x00007FF61C2062C4]\n\t(No symbol) [0x00007FF61C2063F6]\n\t(No symbol) [0x00007FF61C1F67A3]\n\tBaseThreadInitThunk [0x00007FFE43FE7614+20]\n\tRtlUserThreadStart [0x00007FFE45E826B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\add_address.py\", line 42, in step_impl\n    assert context.add_address.verify_text(\"Address saved\")\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\add_address_page.py\", line 50, in verify_text\n    return self.contains(\"add_address_text_xpath\", self.add_address_text_xpath, a)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 15, in contains\n    element = self.get_element(locator_type, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\POC-\\features\\pages\\BasePage.py\", line 46, in get_element\n    element = self.driver.find_element(By.XPATH, locator_value)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 739, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "73b86453-4e90-4f87-9c72-503e3ea0c563-attachment.png", "type": "image/png"}], "start": 1693473474750, "stop": 1693473477946}], "start": 1693473387650, "stop": 1693473481206, "uuid": "c7454729-bf68-42d0-b61c-b402a84bcbbf", "historyId": "12dd1a5d88f4de8a6e7a648477971cb2", "fullName": "print transactions history: adding new address", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "address"}, {"name": "feature", "value": "print transactions history"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}