{"name": "Login with valid phone number and password -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF70B0F4A62+57106]\n\t(No symbol) [0x00007FF70B06CF52]\n\t(No symbol) [0x00007FF70AF3E2CB]\n\t(No symbol) [0x00007FF70AF1DEB9]\n\t(No symbol) [0x00007FF70AF9AE07]\n\t(No symbol) [0x00007FF70AFADBEF]\n\t(No symbol) [0x00007FF70AF96793]\n\t(No symbol) [0x00007FF70AF6CE81]\n\t(No symbol) [0x00007FF70AF6E064]\n\tGetHandleVerifier [0x00007FF70B3A4222+2873042]\n\tGetHandleVerifier [0x00007FF70B3F6590+3209792]\n\tGetHandleVerifier [0x00007FF70B3EF3AF+3180639]\n\tGetHandleVerifier [0x00007FF70B185F25+652245]\n\t(No symbol) [0x00007FF70B078618]\n\t(No symbol) [0x00007FF70B0747C4]\n\t(No symbol) [0x00007FF70B0748BC]\n\t(No symbol) [0x00007FF70B064C33]\n\tBaseThreadInitThunk [0x00007FF965F37614+20]\n\tRtlUserThreadStart [0x00007FF967EE26B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 27, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(),\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I navigated to Login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.171)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00007FF70B0F4A62+57106]\n\t(No symbol) [0x00007FF70B06CF52]\n\t(No symbol) [0x00007FF70AF3E2CB]\n\t(No symbol) [0x00007FF70AF1DEB9]\n\t(No symbol) [0x00007FF70AF9AE07]\n\t(No symbol) [0x00007FF70AFADBEF]\n\t(No symbol) [0x00007FF70AF96793]\n\t(No symbol) [0x00007FF70AF6CE81]\n\t(No symbol) [0x00007FF70AF6E064]\n\tGetHandleVerifier [0x00007FF70B3A4222+2873042]\n\tGetHandleVerifier [0x00007FF70B3F6590+3209792]\n\tGetHandleVerifier [0x00007FF70B3EF3AF+3180639]\n\tGetHandleVerifier [0x00007FF70B185F25+652245]\n\t(No symbol) [0x00007FF70B078618]\n\t(No symbol) [0x00007FF70B0747C4]\n\t(No symbol) [0x00007FF70B0748BC]\n\t(No symbol) [0x00007FF70B064C33]\n\tBaseThreadInitThunk [0x00007FF965F37614+20]\n\tRtlUserThreadStart [0x00007FF967EE26B1+33]\n\n", "trace": "  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features\\environment.py\", line 27, in after_step\n    allure.attach(context.driver.get_screenshot_as_png(),\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\lmallikarjuna\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691653549461, "stop": 1691653549487}, {"name": "When I enter valid phone number as \"8105000676\" and valid password as \"Loki@1234\" into the fields", "status": "skipped", "start": 1691653550897, "stop": 1691653550897}, {"name": "And I click on Login button", "status": "skipped", "start": 1691653550897, "stop": 1691653550897}, {"name": "Then I should get logged in", "status": "skipped", "start": 1691653550897, "stop": 1691653550897}], "parameters": [{"name": "number", "value": "8105000676"}, {"name": "password", "value": "Loki@1234"}], "start": 1691653514241, "stop": 1691653550897, "uuid": "6264d046-ce7d-4af5-a0b8-b81ef2d94cd9", "historyId": "aa0a6f1a55c37fbffdea15f4e9a87916", "fullName": "Login Functionality: Login with valid phone number and password", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "login"}, {"name": "feature", "value": "Login Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}